name: travenor
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  
flutter:
  uses-material-design: true
  fonts:
    - family: sf-ui
      fonts:
        - asset: assets/fonts/SF UI Display/sf-ui-display-semibold-58646eddcae92.otf
        - asset: assets/fonts/SF UI Display/sf-ui-display-ultralight-58646b19bf205.ttf
          weight: 100
        - asset: assets/fonts/SF UI Display/sf-ui-display-thin-58646e9b26e8b.otf
          weight: 200
        - asset: assets/fonts/SF UI Display/sf-ui-display-light-58646b33e0551.otf
          weight: 300
        - asset: assets/fonts/SF UI Display/sf-ui-display-medium-58646be638f96.otf
          weight: 400
        - asset: assets/fonts/SF UI Display/sf-ui-display-bold-58646a511e3d9.otf
          weight: 700
        - asset: assets/fonts/SF UI Display/sf-ui-display-heavy-586470160b9e5.otf
          weight: 800
        - asset: assets/fonts/SF UI Display/sf-ui-display-black-58646a6b80d5a.otf
          weight: 900
    - family: Geometr415 Blk BT
      fonts:
        - asset: assets/fonts/onboarding-fonts/geometric415blackbt/geometric 415 black bt.ttf
    - family: Gill Sans MT
      fonts:
        - asset: assets/fonts/onboarding-fonts/gill-sans-mt.ttf
      
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
